id: P002986
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:32:42.882043
source_metadata:
  id: bdr:W8LS17755
  title: བཀའ་གདམས་སྤྲུལ་པའི་གླེགས་བམ།
  author: ''
  volumes:
    030c1ad3201a4654b2018a931623b143:
      image_group_id: I8LS17780
      title: ''
      volume_number: 1
      total_pages: 460
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
